services:
  - type: web
    name: lantern-store-backend
    env: node
    region: singapore # Change this to your preferred region
    plan: starter # You can upgrade to standard or pro if needed
    buildCommand: npm ci && npm run build && npx prisma generate
    startCommand: node --max-old-space-size=512 dist/main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    # Make sure to add your environment variables in Render dashboard:
    # - DATABASE_URL (your MongoDB connection string)
    # - JWT_SECRET (your JWT secret key)
    # - AWS_REGION (your AWS region)
    # - AWS_ACCESS_KEY_ID (your AWS access key)
    # - AWS_SECRET_ACCESS_KEY (your AWS secret access key)
    # - AWS_S3_BUCKET_NAME (your S3 bucket name) 